namespace MRK {
	public enum EGRLanguageData {
		//ERROR
		ERROR = 0,

		//PASSWORDS MISMATCH
		PASSWORDS_MISMATCH = 1,

		//REGISTER
		REGISTER = 2,

		//FAILED (EGR-{0})
		FAILED__EGR__0__ = 3,

		//FAILED (EGR-{0}-{1})
		FAILED__EGR__0___1__ = 4,

		//REGISTERING...
		REGISTERING___ = 5,

		//SUCCESS
		SUCCESS = 6,

		//LOGGING IN...
		LOGGING_IN___ = 7,

		//LOGIN
		LOGIN = 8,

		//WELCOME {0}
		WELCOME__0_ = 9,

		//INVALID NAME
		INVALID_NAME = 10,

		//SAVING...
		SAVING___ = 11,

		//ACCOUNT INFO
		ACCOUNT_INFO = 12,

		//SAVED
		SAVED = 13,

		//YOU HAVE UNSAVED CHANGES$nWOULD YOU LIKE TO SAVE YOUR CHANGES?
		YOU_HAVE_UNSAVED_CHANGES_nWOULD_YOU_LIKE_TO_SAVE_YOUR_CHANGES_ = 14,

		//YES
		YES = 15,

		//NO
		NO = 16,

		//SAVE
		SAVE = 17,

		//CANCEL
		CANCEL = 18,

		//LOGOUT
		LOGOUT = 19,

		//ARE YOU SURE THAT YOU WANT TO LOGOUT OF EGR?
		ARE_YOU_SURE_THAT_YOU_WANT_TO_LOGOUT_OF_EGR_ = 20,

		//LOGGING IN OFFLINE...
		LOGGING_IN_OFFLINE___ = 21,

		//GRAPHIC SETTINGS WERE MODIFIED$nWOULD YOU LIKE TO APPLY THEM?
		GRAPHIC_SETTINGS_WERE_MODIFIED_nWOULD_YOU_LIKE_TO_APPLY_THEM_ = 22,

		//APPLY
		APPLY = 23,

		//SETTINGS
		SETTINGS = 24,

		//EMAILS DO NOT MATCH
		EMAILS_DO_NOT_MATCH = 25,

		//INVALID EMAIL
		INVALID_EMAIL = 26,

		//ACCOUNTS LINKED WITH A DEVICE ID CAN NOT HAVE THEIR EMAILS CHANGED
		ACCOUNTS_LINKED_WITH_A_DEVICE_ID_CAN_NOT_HAVE_THEIR_EMAILS_CHANGED = 27,

		//INCORRECT PASSWORD
		INCORRECT_PASSWORD = 28,

		//INVALID PASSWORD
		INVALID_PASSWORD = 29,

		//ACCOUNTS LINKED WITH A DEVICE ID CAN NOT HAVE THEIR PASSWORDS CHANGED
		ACCOUNTS_LINKED_WITH_A_DEVICE_ID_CAN_NOT_HAVE_THEIR_PASSWORDS_CHANGED = 30,

		//OK
		OK = 31,

		//NAVIGATION
		NAVIGATION = 32,

		//FINDING AVAILABLE ROUTES
		FINDING_AVAILABLE_ROUTES = 33,

		//LOCATION PERMISSION MUST BE ENABLED TO BE ABLE TO USE CURRENT LOCATION
		LOCATION_PERMISSION_MUST_BE_ENABLED_TO_BE_ABLE_TO_USE_CURRENT_LOCATION = 34,

		//EGR
		EGR = 35,

		//ENABLE
		ENABLE = 36,

		//LOCATION MUST BE ENABLED TO BE ABLE TO USE CURRENT LOCATION
		LOCATION_MUST_BE_ENABLED_TO_BE_ABLE_TO_USE_CURRENT_LOCATION = 37,

		__LANG_DATA_MAX
	}
}
